### ISSUE TITLE
Broken or non-existent link

### ISSUE THREAD

**Issue by mjosborne1** [svelte-society/recipes-mvp#19]
https://github.com/svelte-society/recipes-mvp/blob/master/docs#svelte_store link gives me a 404 error. I accessed this from here https://github.com/svelte-society/recipes-mvp/blob/master/README.md#svelte-store-recipes

I would be very interested in reading more documentation on stores, as I am writing a simple To Do app where I wish to click a link and change the state of a task to Done or Open.
I am yet to see an example of how to update the state for a particular row in a data structure.

**Comment by babycourageous** [comment]
Hi @mjosborne1 

It looks like that TOC link has been fixed as the links to the store recipe in the README both work. 

A full on Todo implementation might be a bit involved for a recipe but here's a quick adaptation of the Svelte tutorial Todo list using a store instead of a local array (animation stuff removed to keep it simple):
https://svelte.dev/repl/354bfb3b58be4e1994901059ee787c2b

I'm going to go ahead and close this - hopefully you got the store info you needed!

Thanks

**Comment by swyxio** [comment]
@mjosborne1 also see #34  - we do need to add more recipes to help out around this area
